<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Lunar\Models\Product;
use Lunar\Models\ProductVariant;
use Lunar\Models\ProductType;
use Lunar\Models\Currency;
use Lunar\Models\Price;
use Lunar\Models\Attribute;
use Lunar\Models\AttributeGroup;
use Lunar\Models\Language;
use Lunar\Models\TaxClass;
use Illuminate\Support\Str;

class LunarProductSeeder extends Seeder
{
    public function run()
    {
        /**
         * 1. Currency
         */
        $currency = Currency::first() ?? Currency::create([
            'name' => 'US Dollar',
            'code' => 'USD',
            'decimal_places' => 2,
            'exchange_rate' => 1,
            'enabled' => true,
            'default' => true,
        ]);

        /**
         * 2. ProductType
         */
        $type = ProductType::first() ?? ProductType::create([
            'name' => 'Default Product Type',
        ]);

        /**
         * 3. AttributeGroup
         */
        $group = AttributeGroup::first() ?? AttributeGroup::create([
            'name' => 'Product Main Data',
            'handle' => 'product_main',
            'position' => 1,
            'attributable_type' => \Lunar\Models\Product::class,
        ]);

        /**
         * 4. Attributes
         */
        $attributes = [
            [
                'handle' => 'name',
                'name' => 'Name',
                'type' => \Lunar\FieldTypes\TranslatedText::class,
                'position' => 1,
            ],
            [
                'handle' => 'description',
                'name' => 'Description',
                'type' => \Lunar\FieldTypes\TranslatedText::class,
                'position' => 2,
            ],
            [
                'handle' => 'release_date',
                'name' => 'Release Date',
                'type' => \Lunar\FieldTypes\Text::class,
                'position' => 3,
            ],
        ];

        foreach ($attributes as $attr) {
            $attribute = Attribute::firstOrCreate(
                ['handle' => $attr['handle']],
                [
                    'name' => $attr['name'],
                    'type' => $attr['type'],
                    'attribute_type' => 'product',
                    'attribute_group_id' => $group->id,
                    'position' => $attr['position'],
                    'required' => false,
                    'configuration' => [],
                    'system' => false,
                ]
            );

            $type->mappedAttributes()->syncWithoutDetaching([$attribute->id]);
        }

        $language = Language::first() ?? Language::create([
            'code' => 'en',
            'name' => 'English',
            'default' => true,
        ]);

        /**
         * 5. Tax Class
         */
        $taxClass = TaxClass::first() ?? TaxClass::create([
            'name' => 'Standard Tax',
            'default' => true,
        ]);

        $adjectives = ['fast', 'silent', 'red', 'bold', 'green', 'rapid', 'wild', 'blue', 'lunar', 'dusty'];
        $nouns      = ['falcon', 'mountain', 'river', 'sky', 'tiger', 'forest', 'ocean', 'engine', 'shadow', 'planet'];

        /**
         * 6. Создаём 3 товара
         */
        for ($i = 1; $i <= 3; $i++) {

            $productName = $adjectives[array_rand($adjectives)]
                . ' '
                . $nouns[array_rand($nouns)];

            $randomPrice = number_format(rand(500, 1500) / 100, 2, '.', '');

            $product = Product::create([
                'status' => 'published',
                'product_type_id' => $type->id,
                'attribute_data' => [
                    'name' => new \Lunar\FieldTypes\TranslatedText([
                        'en' => ucfirst($productName),
                    ]),
                    'description' => new \Lunar\FieldTypes\TranslatedText([
                        'en' => 'Autogenerated product description.',
                    ]),
                    'release_date' => new \Lunar\FieldTypes\Text(
                        now()->toDateString()
                    ),
                ],
            ]);

            // Variant
            $variant = ProductVariant::create([
                'product_id' => $product->id,
                'sku' => 'TEST-' . Str::upper(Str::random(6)),
                'tax_class_id' => $taxClass->id,
            ]);

            // Price
            Price::create([
                'price' => $randomPrice * 100,
                'currency_id' => $currency->id,
                'priceable_type' => ProductVariant::class,
                'priceable_id' => $variant->id,
            ]);
        }
    }
}
